import { Aliases, AliasMap } from '../Types';
import { Category } from '../../../realm/Activity/enum';

// Update, then optimize/format with '../util.getAliassMap()'
// Save output
export const activityCategoryAliases: Aliases<Category> = {
  [Category.Community]: [
    'community',
    'club',
    'event',
    'group',
    'association',
  ],
  [Category.Entertainment]: [
    'entertainment',
    'book',
    'read',
    'television',
    'netflix',
    'youtube',
  ],
  [Category.Fitness]: [
    'fitness',
    'health',
    'lift',
    'workout',
    'exercise',
    'diet',
    'well',
    'hygeine',
    'strength',
    'power',
    'weight',
  ],
  [Category.SocialMedia]: [
    'social media',
    'internet',
    'facebook',
    'instagram',
    'snapchat',
  ],
  [Category.Entrepreneurship]: [
    'entrepreneurship',
    'business',
    'company',
    'start',
    'money',
    'work',
    'job',
    'learn',
  ],
  [Category.Work]: ['work', 'job'],
  [Category.SelfImprovement]: ['self improvement', 'read', 'learn'],
  [Category.Relax]: ['relax', 'beach'],
  [Category.Adventure]: [
    'adventure',
    'explore',
    'event',
    'beach',
    'camp',
  ],
  [Category.Accomplishment]: [
    'accomplishment',
    'goal',
    'success',
    'victory',
    'achieve',
    'won',
  ],
  [Category.Conflict]: [
    'conflict',
    'argument',
    'disagree',
    'fight',
    'anger',
    'mad',
    'sad',
  ],
  [Category.Growth]: ['growth', 'improve', 'success', 'learn'],
  [Category.Competition]: [
    'competition',
    'compete',
    'contest',
    'event',
    'sport',
    'tournament',
    'game',
    'race',
    'match',
    'meet',
  ],
  [Category.Leadership]: [
    'leadership',
    'manage',
    'coach',
    'guide',
    'help',
  ],
  [Category.Athletics]: [
    'athletics',
    'sport',
    'archery',
    'badminton',
    'cricket',
    'bowl',
    'box',
    'curl',
    'tennis',
    'skateboard',
    'surf',
    'hockey',
    'skate',
    'yoga',
    'fence',
    'fit',
    'gymnastics',
    'karate',
    'volleyball',
    'weightlift',
    'basketball',
    'baseball',
    'rugby',
    'wrestle',
    'jump',
    'race',
    'cycle',
    'run',
    'table tennis',
    'judo',
    'climb',
    'shoot',
    'golf',
    'footbal',
    'track',
    'field',
    'swim',
    'cheer',
  ],
  [Category.Volunteer]: ['volunteer', 'help'],
  [Category.Culture]: ['culture'],
  [Category.Art]: [
    'art',
    'sculpt',
    'paint',
    'literature',
    'music',
    'theatre',
    'dance',
    'film',
    'photography',
  ],
  [Category.Dance]: ['dance', 'hiphop'],
  [Category.Academics]: ['academic', 'research', 'science', 'debate'],
  [Category.Religion]: [
    'religion',
    'church',
    'christain',
    'catholic',
    'islam',
    'mass',
    'sabbath',
    'meditate',
  ],
  [Category.Spiritual]: ['spiritual', 'meditate'],
  [Category.Media]: ['media', 'new', 'radio', 'internet'],
  [Category.Politics]: ['politics', 'new', 'govern', 'debate'],
};

// Optimized aliases, one-to-one mapping
export const activityAliasMap: AliasMap<Category> = {
  academ: { name: 'Academics' },
  academic: { name: 'Academics' },
  accomplish: { name: 'Accomplishment' },
  accomplishment: { name: 'Accomplishment' },
  achiev: { name: 'Accomplishment' },
  achieve: { name: 'Accomplishment' },
  adventur: { name: 'Adventure' },
  adventure: { name: 'Adventure' },
  anger: { name: 'Conflict' },
  archeri: { name: 'Athletics' },
  archery: { name: 'Athletics' },
  argument: { name: 'Conflict' },
  art: { name: 'Art' },
  associ: { name: 'Community' },
  association: { name: 'Community' },
  athlet: { name: 'Athletics' },
  athletics: { name: 'Athletics' },
  badminton: { name: 'Athletics' },
  basebal: { name: 'Athletics' },
  baseball: { name: 'Athletics' },
  basketbal: { name: 'Athletics' },
  basketball: { name: 'Athletics' },
  beach: { name: 'Adventure' },
  book: { name: 'Entertainment' },
  bowl: { name: 'Athletics' },
  box: { name: 'Athletics' },
  busi: { name: 'Entrepreneurship' },
  business: { name: 'Entrepreneurship' },
  camp: { name: 'Adventure' },
  cathol: { name: 'Religion' },
  catholic: { name: 'Religion' },
  cheer: { name: 'Athletics' },
  christain: { name: 'Religion' },
  church: { name: 'Religion' },
  climb: { name: 'Athletics' },
  club: { name: 'Community' },
  coach: { name: 'Leadership' },
  commun: { name: 'Community' },
  community: { name: 'Community' },
  compani: { name: 'Entrepreneurship' },
  company: { name: 'Entrepreneurship' },
  compet: { name: 'Competition' },
  compete: { name: 'Competition' },
  competit: { name: 'Competition' },
  competition: { name: 'Competition' },
  conflict: { name: 'Conflict' },
  contest: { name: 'Competition' },
  cricket: { name: 'Athletics' },
  cultur: { name: 'Culture' },
  culture: { name: 'Culture' },
  curl: { name: 'Athletics' },
  cycl: { name: 'Athletics' },
  cycle: { name: 'Athletics' },
  danc: { name: 'Dance' },
  dance: { name: 'Dance' },
  debat: { name: 'Politics' },
  debate: { name: 'Politics' },
  diet: { name: 'Fitness' },
  disagre: { name: 'Conflict' },
  disagree: { name: 'Conflict' },
  entertain: { name: 'Entertainment' },
  entertainment: { name: 'Entertainment' },
  entrepreneurship: { name: 'Entrepreneurship' },
  event: { name: 'Competition' },
  exercis: { name: 'Fitness' },
  exercise: { name: 'Fitness' },
  explor: { name: 'Adventure' },
  explore: { name: 'Adventure' },
  facebook: { name: 'SocialMedia' },
  fenc: { name: 'Athletics' },
  fence: { name: 'Athletics' },
  field: { name: 'Athletics' },
  fight: { name: 'Conflict' },
  film: { name: 'Art' },
  fit: { name: 'Athletics' },
  fitness: { name: 'Fitness' },
  footbal: { name: 'Athletics' },
  game: { name: 'Competition' },
  goal: { name: 'Accomplishment' },
  golf: { name: 'Athletics' },
  govern: { name: 'Politics' },
  group: { name: 'Community' },
  growth: { name: 'Growth' },
  guid: { name: 'Leadership' },
  guide: { name: 'Leadership' },
  gymnast: { name: 'Athletics' },
  gymnastics: { name: 'Athletics' },
  health: { name: 'Fitness' },
  help: { name: 'Volunteer' },
  hiphop: { name: 'Dance' },
  hockei: { name: 'Athletics' },
  hockey: { name: 'Athletics' },
  hygein: { name: 'Fitness' },
  hygeine: { name: 'Fitness' },
  improv: { name: 'Growth' },
  improve: { name: 'Growth' },
  instagram: { name: 'SocialMedia' },
  internet: { name: 'Media' },
  islam: { name: 'Religion' },
  job: { name: 'Work' },
  judo: { name: 'Athletics' },
  jump: { name: 'Athletics' },
  karat: { name: 'Athletics' },
  karate: { name: 'Athletics' },
  leadership: { name: 'Leadership' },
  learn: { name: 'Growth' },
  lift: { name: 'Fitness' },
  literatur: { name: 'Art' },
  literature: { name: 'Art' },
  mad: { name: 'Conflict' },
  manag: { name: 'Leadership' },
  manage: { name: 'Leadership' },
  mass: { name: 'Religion' },
  match: { name: 'Competition' },
  media: { name: 'Media' },
  medit: { name: 'Spiritual' },
  meditate: { name: 'Spiritual' },
  meet: { name: 'Competition' },
  monei: { name: 'Entrepreneurship' },
  money: { name: 'Entrepreneurship' },
  music: { name: 'Art' },
  netflix: { name: 'Entertainment' },
  new: { name: 'Politics' },
  paint: { name: 'Art' },
  photographi: { name: 'Art' },
  photography: { name: 'Art' },
  polit: { name: 'Politics' },
  politics: { name: 'Politics' },
  power: { name: 'Fitness' },
  race: { name: 'Athletics' },
  radio: { name: 'Media' },
  read: { name: 'Self Improvement' },
  relax: { name: 'Relax' },
  religion: { name: 'Religion' },
  research: { name: 'Academics' },
  rugbi: { name: 'Athletics' },
  rugby: { name: 'Athletics' },
  run: { name: 'Athletics' },
  sabbath: { name: 'Religion' },
  sad: { name: 'Conflict' },
  scienc: { name: 'Academics' },
  science: { name: 'Academics' },
  sculpt: { name: 'Art' },
  'self improv': { name: 'Self Improvement' },
  'self improvement': { name: 'Self Improvement' },
  shoot: { name: 'Athletics' },
  skate: { name: 'Athletics' },
  skateboard: { name: 'Athletics' },
  snapchat: { name: 'SocialMedia' },
  'social media': { name: 'SocialMedia' },
  spiritu: { name: 'Spiritual' },
  spiritual: { name: 'Spiritual' },
  sport: { name: 'Athletics' },
  start: { name: 'Entrepreneurship' },
  strength: { name: 'Fitness' },
  success: { name: 'Growth' },
  surf: { name: 'Athletics' },
  swim: { name: 'Athletics' },
  'table tenni': { name: 'Athletics' },
  'table tennis': { name: 'Athletics' },
  televis: { name: 'Entertainment' },
  television: { name: 'Entertainment' },
  tenni: { name: 'Athletics' },
  tennis: { name: 'Athletics' },
  theatr: { name: 'Art' },
  theatre: { name: 'Art' },
  tournament: { name: 'Competition' },
  track: { name: 'Athletics' },
  victori: { name: 'Accomplishment' },
  victory: { name: 'Accomplishment' },
  volleybal: { name: 'Athletics' },
  volleyball: { name: 'Athletics' },
  volunt: { name: 'Volunteer' },
  volunteer: { name: 'Volunteer' },
  weight: { name: 'Fitness' },
  weightlift: { name: 'Athletics' },
  well: { name: 'Fitness' },
  won: { name: 'Accomplishment' },
  work: { name: 'Work' },
  workout: { name: 'Fitness' },
  wrestl: { name: 'Athletics' },
  wrestle: { name: 'Athletics' },
  yoga: { name: 'Athletics' },
  youtub: { name: 'Entertainment' },
  youtube: { name: 'Entertainment' },
};
